import type { DailyQuestion } from './types'

export const DAILY_QUESTIONS: DailyQuestion[] = [
  // ── usestate-basic ──────────────────────────────────
  {
    id: 'usestate-basic-daily-0',
    stepId: 'usestate-basic',
    type: 'blank',
    prompt: 'useState を使って count という状態変数を宣言してください。\nconst [count, ____] = useState(0)',
    answer: 'setCount',
    hint: 'セッター関数の命名規則は set + 変数名（先頭大文字）です。',
    explanation: 'useState は [状態変数, セッター関数] の配列を返します。セッター関数は慣例的に set + 変数名（先頭大文字）と命名します。',
  },
  {
    id: 'usestate-basic-daily-1',
    stepId: 'usestate-basic',
    type: 'choice',
    prompt: 'useState の初期値として文字列 "hello" を設定するコードはどれですか？',
    answer: 'const [text, setText] = useState("hello")',
    hint: 'useState の引数が初期値になります。',
    explanation: 'useState の引数に初期値を渡します。文字列・数値・オブジェクトなど任意の値を初期値として指定できます。',
    choices: [
      'const [text, setText] = useState("hello")',
      'const [text, setText] = useState()',
      'const text = useState("hello")',
      'const [text] = useState("hello")',
    ],
  },
  {
    id: 'usestate-basic-daily-2',
    stepId: 'usestate-basic',
    type: 'blank',
    prompt: 'ボタンをクリックするたびに count を 1 増やすハンドラを完成させてください。\nconst handleClick = () => {\n  ____(count + 1)\n}',
    answer: 'setCount',
    hint: 'セッター関数を呼び出して状態を更新します。',
    explanation: 'useState のセッター関数（setCount）に新しい値を渡すことで状態が更新され、コンポーネントが再レンダリングされます。',
  },

  // ── events ──────────────────────────────────────────
  {
    id: 'events-daily-0',
    stepId: 'events',
    type: 'blank',
    prompt: 'ボタンのクリックイベントを処理するコードを完成させてください。\n<button ____={handleClick}>クリック</button>',
    answer: 'onClick',
    hint: 'React のクリックイベントハンドラはキャメルケースで記述します。',
    explanation: 'React では DOM イベント名をキャメルケースにした onClick などを使います。HTML の onclick とは異なります。',
  },
  {
    id: 'events-daily-1',
    stepId: 'events',
    type: 'choice',
    prompt: 'フォームのデフォルト送信動作をキャンセルするメソッドはどれですか？',
    answer: 'e.preventDefault()',
    hint: 'イベントオブジェクトのメソッドを使います。',
    explanation: 'e.preventDefault() を呼ぶことでフォームのページリロードなどデフォルト動作をキャンセルできます。',
    choices: [
      'e.preventDefault()',
      'e.stopPropagation()',
      'e.cancelBubble()',
      'e.returnValue(false)',
    ],
  },
  {
    id: 'events-daily-2',
    stepId: 'events',
    type: 'blank',
    prompt: 'input の変更を検知するイベントを完成させてください。\n<input ____={handleChange} />',
    answer: 'onChange',
    hint: '入力値の変化を検知する React イベントです。',
    explanation: 'onChange は入力フィールドの値が変わるたびに発火します。React では制御コンポーネントの実装に必須のイベントです。',
  },

  // ── conditional ─────────────────────────────────────
  {
    id: 'conditional-daily-0',
    stepId: 'conditional',
    type: 'blank',
    prompt: '三項演算子で isLoggedIn が true の場合に "ようこそ" を表示してください。\n{isLoggedIn ____ "ようこそ" : "ログインしてください"}',
    answer: '?',
    hint: '三項演算子の構文は 条件 ? 真の値 : 偽の値 です。',
    explanation: '三項演算子 ? : を使うと JSX 内でインラインの条件分岐ができます。if 文は JSX 内では直接使えないため三項演算子か && が使われます。',
  },
  {
    id: 'conditional-daily-1',
    stepId: 'conditional',
    type: 'choice',
    prompt: '短絡評価で isAdmin が true のときだけ <AdminPanel /> を表示するコードはどれですか？',
    answer: '{isAdmin && <AdminPanel />}',
    hint: '&& 演算子の左辺が falsy なら右辺は評価されません。',
    explanation: '&&（論理積）演算子を使うと、左辺が true のときだけ右辺を表示できます。else 不要なシンプルな条件表示に適しています。',
    choices: [
      '{isAdmin && <AdminPanel />}',
      '{isAdmin || <AdminPanel />}',
      '{isAdmin ? <AdminPanel /> : null}',
      '{isAdmin == true && <AdminPanel />}',
    ],
  },
  {
    id: 'conditional-daily-2',
    stepId: 'conditional',
    type: 'blank',
    prompt: '何も表示しないために JSX で返せる値を入力してください。\nreturn isHidden ? ____ : <div>表示</div>',
    answer: 'null',
    hint: 'React では何も描画しないことを null で表現します。',
    explanation: 'JSX で null を返すとコンポーネントは何も描画しません。undefined や false も描画されませんが、明示的に null を使うのが慣例です。',
  },

  // ── lists ────────────────────────────────────────────
  {
    id: 'lists-daily-0',
    stepId: 'lists',
    type: 'blank',
    prompt: 'リスト要素に必須の属性を追加してください。\nitems.map(item => <li ____={item.id}>{item.name}</li>)',
    answer: 'key',
    hint: 'React がリスト要素を識別するために使う特殊な属性です。',
    explanation: 'key prop は React が差分検出アルゴリズムで各リスト要素を一意に識別するために必要です。一意の識別子（ID など）を使います。',
  },
  {
    id: 'lists-daily-1',
    stepId: 'lists',
    type: 'choice',
    prompt: '配列の各要素を JSX に変換するために使うメソッドはどれですか？',
    answer: 'map',
    hint: '各要素を別の値に変換して新しい配列を返すメソッドです。',
    explanation: 'Array.prototype.map は各要素に関数を適用して新しい配列を返します。React のリスト描画では map を使って JSX 要素の配列を生成します。',
    choices: ['map', 'forEach', 'reduce', 'filter'],
  },
  {
    id: 'lists-daily-2',
    stepId: 'lists',
    type: 'blank',
    prompt: '偶数の要素だけ表示するために配列を絞り込んでください。\nconst evens = numbers.____(n => n % 2 === 0)',
    answer: 'filter',
    hint: '条件に一致する要素だけを残すメソッドです。',
    explanation: 'Array.prototype.filter は条件関数が true を返す要素だけを含む新しい配列を返します。map と組み合わせてリスト表示の絞り込みに使います。',
  },

  // ── useeffect ────────────────────────────────────────
  {
    id: 'useeffect-daily-0',
    stepId: 'useeffect',
    type: 'blank',
    prompt: 'マウント時に一度だけ処理を実行する useEffect を完成させてください。\nuseEffect(() => {\n  fetchData()\n}, ____)',
    answer: '[]',
    hint: '依存配列を空にすると初回レンダリング時のみ実行されます。',
    explanation: '依存配列 [] を渡すと useEffect はコンポーネントのマウント時に一度だけ実行されます。配列を省略すると毎レンダリング後に実行されます。',
  },
  {
    id: 'useeffect-daily-1',
    stepId: 'useeffect',
    type: 'choice',
    prompt: 'useEffect でイベントリスナーを登録した後、アンマウント時に解除するために使うのはどれですか？',
    answer: 'クリーンアップ関数（return () => { ... }）を返す',
    hint: 'useEffect のコールバックから関数を return できます。',
    explanation: 'useEffect のコールバックから関数を return すると、コンポーネントのアンマウント時やエフェクトが再実行される前にその関数が呼ばれます。リソースの解放に使います。',
    choices: [
      'クリーンアップ関数（return () => { ... }）を返す',
      'useEffect の第3引数に解除関数を渡す',
      'useUnmount フックを使う',
      'componentWillUnmount を定義する',
    ],
  },
  {
    id: 'useeffect-daily-2',
    stepId: 'useeffect',
    type: 'blank',
    prompt: 'userId が変わるたびにデータを再取得する useEffect を完成させてください。\nuseEffect(() => {\n  fetchUser(userId)\n}, [____])',
    answer: 'userId',
    hint: '依存配列に含めた値が変化したときにエフェクトが再実行されます。',
    explanation: '依存配列に userId を含めると、userId の値が変わるたびに useEffect が再実行されます。依存値を適切に指定することでバグを防げます。',
  },

  // ── forms ────────────────────────────────────────────
  {
    id: 'forms-daily-0',
    stepId: 'forms',
    type: 'blank',
    prompt: '制御コンポーネントで input の現在値を管理してください。\n<input value={inputValue} onChange={e => setInputValue(e.target.____)} />',
    answer: 'value',
    hint: 'イベントオブジェクトのターゲット要素の値プロパティです。',
    explanation: 'e.target.value で input 要素の現在の値を取得できます。これを状態にセットすることで React が値を管理する「制御コンポーネント」になります。',
  },
  {
    id: 'forms-daily-1',
    stepId: 'forms',
    type: 'choice',
    prompt: 'フォーム送信時のデフォルト動作（ページリロード）を防ぐために必要な処理はどれですか？',
    answer: 'e.preventDefault() を onSubmit ハンドラ内で呼ぶ',
    hint: 'デフォルトのフォーム送信動作をキャンセルします。',
    explanation: 'フォームの onSubmit ハンドラで e.preventDefault() を呼ぶことで、HTML フォームのデフォルト動作（ページリロード・サーバー送信）をキャンセルします。',
    choices: [
      'e.preventDefault() を onSubmit ハンドラ内で呼ぶ',
      'type="submit" を削除する',
      'form タグを div に変える',
      'return false を返す',
    ],
  },
  {
    id: 'forms-daily-2',
    stepId: 'forms',
    type: 'blank',
    prompt: 'フォーム送信時にハンドラを実行するイベントを設定してください。\n<form ____={handleSubmit}>',
    answer: 'onSubmit',
    hint: 'フォームの送信イベントを処理する React イベントです。',
    explanation: 'onSubmit はフォームが送信されたときに発火するイベントです。Enter キーでの送信やサブミットボタンのクリックで発火します。',
  },

  // ── usecontext ───────────────────────────────────────
  {
    id: 'usecontext-daily-0',
    stepId: 'usecontext',
    type: 'blank',
    prompt: 'コンテキストを作成してください。\nconst ThemeContext = ____(\'light\')',
    answer: 'createContext',
    hint: 'React のコンテキストを生成する関数です。',
    explanation: 'createContext は React からインポートする関数で、コンテキストオブジェクトを作成します。引数がデフォルト値になります。',
  },
  {
    id: 'usecontext-daily-1',
    stepId: 'usecontext',
    type: 'choice',
    prompt: 'コンテキストの値をコンポーネントで読み取るフックはどれですか？',
    answer: 'useContext',
    hint: 'コンテキストの値を消費するフックです。',
    explanation: 'useContext(MyContext) でコンテキストの現在値を取得できます。最も近い Provider の value prop が返されます。',
    choices: ['useContext', 'useState', 'useRef', 'useReducer'],
  },
  {
    id: 'usecontext-daily-2',
    stepId: 'usecontext',
    type: 'blank',
    prompt: 'コンテキストを子コンポーネントに提供するコードを完成させてください。\n<ThemeContext.____ value={theme}>\n  {children}\n</ThemeContext.____>',
    answer: 'Provider',
    hint: 'コンテキストオブジェクトのプロパティです。',
    explanation: 'Context.Provider で囲まれたすべての子コンポーネントがその value にアクセスできます。value が変わると配下のコンポーネントが再レンダリングされます。',
  },

  // ── usereducer ───────────────────────────────────────
  {
    id: 'usereducer-daily-0',
    stepId: 'usereducer',
    type: 'blank',
    prompt: 'useReducer のアクションをディスパッチしてください。\n____(({ type: \'INCREMENT\' }))',
    answer: 'dispatch',
    hint: 'useReducer が返す状態更新のトリガー関数です。',
    explanation: 'dispatch 関数にアクションオブジェクトを渡すと、reducer 関数が呼ばれて新しい状態が計算されます。',
  },
  {
    id: 'usereducer-daily-1',
    stepId: 'usereducer',
    type: 'choice',
    prompt: 'useReducer の reducer 関数のシグネチャはどれですか？',
    answer: '(state, action) => newState',
    hint: 'reducer は現在の状態とアクションを受け取り新しい状態を返します。',
    explanation: 'reducer は (state, action) => newState という純粋関数です。副作用なしで現在の状態とアクションから次の状態を計算します。',
    choices: [
      '(state, action) => newState',
      '(action) => newState',
      '(state) => newState',
      '(dispatch, state) => newState',
    ],
  },
  {
    id: 'usereducer-daily-2',
    stepId: 'usereducer',
    type: 'blank',
    prompt: 'reducer でアクションの種類を判定してください。\nswitch (action.____) {\n  case \'INCREMENT\': ...\n}',
    answer: 'type',
    hint: 'アクションオブジェクトの種類を示す慣例的なプロパティです。',
    explanation: 'action.type はアクションの種類を示す文字列です。switch 文でアクションタイプごとに異なる状態更新ロジックを実装します。',
  },

  // ── custom-hooks ─────────────────────────────────────
  {
    id: 'custom-hooks-daily-0',
    stepId: 'custom-hooks',
    type: 'blank',
    prompt: 'カスタムフックの関数名として正しい命名プレフィックスを入力してください。\nfunction ____Counter() { ... }',
    answer: 'use',
    hint: 'React のフックは必ずこの文字で始まります。',
    explanation: 'カスタムフックは use で始まる関数として定義します。この命名規則により React がフックのルール（条件分岐内での呼び出し禁止等）を静的解析で検証できます。',
  },
  {
    id: 'custom-hooks-daily-1',
    stepId: 'custom-hooks',
    type: 'choice',
    prompt: 'カスタムフックの主な目的はどれですか？',
    answer: 'ステートフルなロジックを複数のコンポーネント間で再利用する',
    hint: 'コンポーネント間でのコード共有について考えてください。',
    explanation: 'カスタムフックは useState や useEffect などのフックを使ったロジックを関数として切り出し、複数のコンポーネントで再利用できるようにします。',
    choices: [
      'ステートフルなロジックを複数のコンポーネント間で再利用する',
      'グローバル状態を管理する',
      'コンポーネントの描画をスキップする',
      'サーバーとの通信を最適化する',
    ],
  },
  {
    id: 'custom-hooks-daily-2',
    stepId: 'custom-hooks',
    type: 'blank',
    prompt: 'カスタムフック useInput が入力値と onChange ハンドラを返すコードを完成させてください。\nfunction useInput(initial) {\n  const [value, setValue] = useState(initial)\n  const onChange = e => setValue(e.target.value)\n  return { ____, onChange }\n}',
    answer: 'value',
    hint: '状態変数を返します。',
    explanation: 'カスタムフックは使いたい値や関数をオブジェクトや配列で return します。呼び出し側はその戻り値を分割代入で受け取ります。',
  },

  // ── api-fetch ────────────────────────────────────────
  {
    id: 'api-fetch-daily-0',
    stepId: 'api-fetch',
    type: 'blank',
    prompt: 'HTTP リクエストを送る組み込み関数を使ってください。\nconst response = await ____(\'/api/users\')',
    answer: 'fetch',
    hint: 'ブラウザに組み込まれた HTTP リクエスト関数です。',
    explanation: 'fetch() は Promise を返すブラウザ組み込みの HTTP クライアント関数です。await と組み合わせて非同期処理をシンプルに書けます。',
  },
  {
    id: 'api-fetch-daily-1',
    stepId: 'api-fetch',
    type: 'choice',
    prompt: 'fetch のレスポンスを JSON として解析するメソッドはどれですか？',
    answer: 'response.json()',
    hint: 'Response オブジェクトのメソッドです。',
    explanation: 'response.json() は Response ボディを JSON としてパースし Promise を返します。await response.json() で結果を受け取れます。',
    choices: [
      'response.json()',
      'JSON.parse(response)',
      'response.data',
      'response.text()',
    ],
  },
  {
    id: 'api-fetch-daily-2',
    stepId: 'api-fetch',
    type: 'blank',
    prompt: 'データ取得時のエラーをキャッチしてください。\ntry {\n  const data = await fetchData()\n} ____ (error) {\n  setError(error.message)\n}',
    answer: 'catch',
    hint: '非同期エラーを捕捉する構文です。',
    explanation: 'try-catch で非同期エラーをキャッチします。fetch はネットワークエラー時に例外をスローするため、catch ブロックでエラー状態を設定します。',
  },

  // ── performance ──────────────────────────────────────
  {
    id: 'performance-daily-0',
    stepId: 'performance',
    type: 'blank',
    prompt: '計算コストの高い値をメモ化してください。\nconst result = ____(()=> expensiveCalc(input), [input])',
    answer: 'useMemo',
    hint: '値をメモ化する React フックです。',
    explanation: 'useMemo は依存配列の値が変わらない限り計算結果をキャッシュします。レンダリングのたびに重い計算が走るのを防ぎます。',
  },
  {
    id: 'performance-daily-1',
    stepId: 'performance',
    type: 'choice',
    prompt: 'コールバック関数をメモ化するフックはどれですか？',
    answer: 'useCallback',
    hint: '関数の参照を安定させるフックです。',
    explanation: 'useCallback は依存配列が変わらない限り同じ関数参照を返します。子コンポーネントへのコールバック渡しで不要な再レンダリングを防ぎます。',
    choices: ['useCallback', 'useMemo', 'useRef', 'useEffect'],
  },
  {
    id: 'performance-daily-2',
    stepId: 'performance',
    type: 'blank',
    prompt: 'props が変わらない限り再レンダリングをスキップするコンポーネントを作ってください。\nexport const MyComponent = React.____(({ name }) => {\n  return <div>{name}</div>\n})',
    answer: 'memo',
    hint: 'コンポーネントをメモ化する React の高階関数です。',
    explanation: 'React.memo はコンポーネントをラップし、props が前回と同じなら再レンダリングをスキップします。純粋な表示コンポーネントのパフォーマンス改善に有効です。',
  },

  // ── testing ──────────────────────────────────────────
  {
    id: 'testing-daily-0',
    stepId: 'testing',
    type: 'blank',
    prompt: 'Testing Library でコンポーネントを描画してください。\nconst { getByText } = ____(<MyComponent />)',
    answer: 'render',
    hint: 'Testing Library のコンポーネント描画関数です。',
    explanation: 'render() は @testing-library/react が提供するコンポーネント描画関数です。DOM にコンポーネントをマウントし、クエリ関数を返します。',
  },
  {
    id: 'testing-daily-1',
    stepId: 'testing',
    type: 'choice',
    prompt: '「ボタン」という名前のボタン要素を取得するクエリはどれですか？',
    answer: 'getByRole("button", { name: "ボタン" })',
    hint: 'アクセシビリティロールと名前で要素を取得します。',
    explanation: 'getByRole はアクセシブルロールで要素を取得します。name オプションでアクセシブルネーム（aria-label やテキスト）を指定して絞り込めます。',
    choices: [
      'getByRole("button", { name: "ボタン" })',
      'getByText("ボタン")',
      'getById("button")',
      'querySelector("button")',
    ],
  },
  {
    id: 'testing-daily-2',
    stepId: 'testing',
    type: 'blank',
    prompt: '値が true であることをアサートしてください。\n____（isVisible).toBe(true)',
    answer: 'expect(',
    hint: 'Vitest/Jest のアサーション関数です。',
    explanation: 'expect() は Vitest/Jest のアサーション関数です。チェーンで toBe・toEqual・toContain などのマッチャーを続けて期待値と比較します。',
  },

  // ── api-counter-get ──────────────────────────────────
  {
    id: 'api-counter-get-daily-0',
    stepId: 'api-counter-get',
    type: 'blank',
    prompt: 'GET リクエストでカウンター値を取得してください。\nconst res = await ____(\'/counter\')',
    answer: 'fetch',
    hint: 'ブラウザ組み込みの HTTP リクエスト関数です。',
    explanation: 'fetch() に URL を渡すとデフォルトで GET リクエストを送ります。await で Promise の解決を待ちます。',
  },
  {
    id: 'api-counter-get-daily-1',
    stepId: 'api-counter-get',
    type: 'choice',
    prompt: 'ローディング中に表示する状態変数の初期値として適切なのはどれですか？',
    answer: 'true',
    hint: 'データ取得開始時はローディング中です。',
    explanation: 'ローディング状態の初期値を true にすることで、コンポーネントがマウントされた直後からローディング表示ができ、データ取得後に false にします。',
    choices: ['true', 'false', 'null', '0'],
  },
  {
    id: 'api-counter-get-daily-2',
    stepId: 'api-counter-get',
    type: 'blank',
    prompt: 'レスポンスを JSON に変換してください。\nconst data = await res.____()',
    answer: 'json',
    hint: 'Response オブジェクトの JSON パースメソッドです。',
    explanation: 'res.json() は Response ボディを JSON としてパースした値の Promise を返します。',
  },

  // ── api-counter-post ─────────────────────────────────
  {
    id: 'api-counter-post-daily-0',
    stepId: 'api-counter-post',
    type: 'blank',
    prompt: 'POST リクエストを送るために method を指定してください。\nfetch(\'/counter/increment\', {\n  ____: \'POST\',\n})',
    answer: 'method',
    hint: 'fetch の第2引数にオプションを渡します。',
    explanation: 'fetch の第2引数のオブジェクトに method プロパティで HTTP メソッドを指定します。デフォルトは GET です。',
  },
  {
    id: 'api-counter-post-daily-1',
    stepId: 'api-counter-post',
    type: 'choice',
    prompt: 'JSON ボディを送るために必要な Content-Type ヘッダーはどれですか？',
    answer: 'application/json',
    hint: 'JSON データの MIME タイプです。',
    explanation: 'Content-Type: application/json を指定することでサーバーにリクエストボディが JSON 形式であることを伝えます。',
    choices: [
      'application/json',
      'text/plain',
      'multipart/form-data',
      'application/x-www-form-urlencoded',
    ],
  },
  {
    id: 'api-counter-post-daily-2',
    stepId: 'api-counter-post',
    type: 'blank',
    prompt: 'オブジェクトを JSON 文字列に変換してください。\nbody: ____({{ amount: 1 }})',
    answer: 'JSON.stringify',
    hint: 'JavaScript オブジェクトを JSON 文字列にシリアライズする関数です。',
    explanation: 'fetch の body には文字列を渡す必要があります。JSON.stringify() でオブジェクトを JSON 文字列に変換してから渡します。',
  },

  // ── api-tasks-list ───────────────────────────────────
  {
    id: 'api-tasks-list-daily-0',
    stepId: 'api-tasks-list',
    type: 'blank',
    prompt: 'タスク一覧を取得して状態に保存してください。\nconst res = await fetch(\'/tasks\')\nconst data = await res.json()\n____(data)',
    answer: 'setTasks',
    hint: 'タスクの配列を状態に保存するセッター関数です。',
    explanation: 'fetch でデータを取得した後、useState のセッター関数で状態を更新するとコンポーネントが再レンダリングされ取得データが表示されます。',
  },
  {
    id: 'api-tasks-list-daily-1',
    stepId: 'api-tasks-list',
    type: 'choice',
    prompt: 'タスク一覧の初期取得を行う適切な場所はどれですか？',
    answer: 'useEffect の依存配列を [] にして実行する',
    hint: 'マウント時に一度だけ実行する方法です。',
    explanation: '依存配列が [] の useEffect はコンポーネントのマウント時に一度だけ実行されます。初回データ取得の定番パターンです。',
    choices: [
      'useEffect の依存配列を [] にして実行する',
      'コンポーネント関数の最上位で直接 fetch を呼ぶ',
      'onClick イベントで fetch を呼ぶ',
      'useState の初期値関数で fetch を呼ぶ',
    ],
  },
  {
    id: 'api-tasks-list-daily-2',
    stepId: 'api-tasks-list',
    type: 'blank',
    prompt: 'タスクの配列を管理する状態を初期化してください。\nconst [tasks, setTasks] = useState(____)',
    answer: '[]',
    hint: 'タスクがない初期状態は空の配列です。',
    explanation: 'リスト表示の状態は空配列 [] で初期化するのが一般的です。ローディング中は空配列が表示されるためエラーになりません。',
  },

  // ── api-tasks-create ─────────────────────────────────
  {
    id: 'api-tasks-create-daily-0',
    stepId: 'api-tasks-create',
    type: 'blank',
    prompt: '新しいタスクを作成する POST リクエストのメソッドを指定してください。\nfetch(\'/tasks\', { ____: \'POST\', ... })',
    answer: 'method',
    hint: 'fetch オプションの HTTP メソッド指定プロパティです。',
    explanation: '新しいリソースの作成には HTTP の POST メソッドを使います。fetch の method プロパティで指定します。',
  },
  {
    id: 'api-tasks-create-daily-1',
    stepId: 'api-tasks-create',
    type: 'choice',
    prompt: '作成成功後にタスク一覧を更新する適切な方法はどれですか？',
    answer: 'setTasks(prev => [...prev, newTask]) で既存タスクに追加する',
    hint: '既存の状態を保持しながら新しい要素を追加します。',
    explanation: 'setTasks に関数を渡すと前の状態 prev を受け取れます。スプレッド構文で既存の配列をコピーしつつ新しいタスクを末尾に追加します。',
    choices: [
      'setTasks(prev => [...prev, newTask]) で既存タスクに追加する',
      'setTasks([newTask]) で置き換える',
      '再度 fetch してリスト全体を取得し直す',
      'window.location.reload() でページを更新する',
    ],
  },
  {
    id: 'api-tasks-create-daily-2',
    stepId: 'api-tasks-create',
    type: 'blank',
    prompt: 'サーバーから返されたタスクを既存リストに追加してください。\nconst created = await res.json()\nsetTasks(prev => [____, created])',
    answer: '...prev',
    hint: 'スプレッド構文で既存配列を展開します。',
    explanation: 'スプレッド構文 ...prev で前の配列の全要素を展開し、created を末尾に追加した新しい配列を作ります。',
  },

  // ── api-tasks-update ─────────────────────────────────
  {
    id: 'api-tasks-update-daily-0',
    stepId: 'api-tasks-update',
    type: 'blank',
    prompt: 'ID が 1 のタスクを更新する PUT リクエストを送ってください。\nfetch(\'/tasks/1\', { ____: \'PUT\', ... })',
    answer: 'method',
    hint: 'リソースの更新には PUT または PATCH を使います。',
    explanation: 'PUT はリソース全体を置き換え、PATCH は一部を更新します。fetch の method プロパティで指定します。',
  },
  {
    id: 'api-tasks-update-daily-1',
    stepId: 'api-tasks-update',
    type: 'choice',
    prompt: 'タスク一覧の中で ID が一致するタスクだけを更新する方法はどれですか？',
    answer: 'tasks.map(t => t.id === id ? updatedTask : t)',
    hint: 'map で各要素を処理し、一致する要素だけ置き換えます。',
    explanation: 'map を使って配列全体を走査し、ID が一致するタスクだけ更新後のオブジェクトに置き換えます。他のタスクはそのまま返します。',
    choices: [
      'tasks.map(t => t.id === id ? updatedTask : t)',
      'tasks.filter(t => t.id !== id).push(updatedTask)',
      'tasks.splice(index, 1, updatedTask)',
      'tasks.find(t => t.id === id) = updatedTask',
    ],
  },
  {
    id: 'api-tasks-update-daily-2',
    stepId: 'api-tasks-update',
    type: 'blank',
    prompt: '更新対象タスクをマージしてリクエストボディを作ってください。\nbody: JSON.stringify({ ____task, done: true })',
    answer: '...',
    hint: 'スプレッド構文でオブジェクトのプロパティを展開します。',
    explanation: 'スプレッド構文 ...task で既存オブジェクトのプロパティを展開し、done: true で上書きした新しいオブジェクトを作ります。',
  },

  // ── api-tasks-delete ─────────────────────────────────
  {
    id: 'api-tasks-delete-daily-0',
    stepId: 'api-tasks-delete',
    type: 'blank',
    prompt: 'ID が 1 のタスクを削除する DELETE リクエストを送ってください。\nfetch(\'/tasks/1\', { ____: \'DELETE\' })',
    answer: 'method',
    hint: 'リソースの削除には DELETE メソッドを使います。',
    explanation: 'DELETE メソッドは指定したリソースの削除をサーバーにリクエストします。',
  },
  {
    id: 'api-tasks-delete-daily-1',
    stepId: 'api-tasks-delete',
    type: 'choice',
    prompt: '削除したタスクをリストから取り除く方法はどれですか？',
    answer: 'tasks.filter(t => t.id !== deletedId)',
    hint: '条件に一致しない要素だけを残します。',
    explanation: 'filter で削除したタスクの ID 以外の要素だけを残した新しい配列を作り、setTasks に渡して状態を更新します。',
    choices: [
      'tasks.filter(t => t.id !== deletedId)',
      'tasks.splice(index, 1)',
      'delete tasks[index]',
      'tasks.remove(deletedId)',
    ],
  },
  {
    id: 'api-tasks-delete-daily-2',
    stepId: 'api-tasks-delete',
    type: 'blank',
    prompt: '削除後にタスク一覧から該当タスクを除外してください。\nsetTasks(prev => prev.____(t => t.id !== id))',
    answer: 'filter',
    hint: '条件を満たす要素だけを残す配列メソッドです。',
    explanation: 'filter(t => t.id !== id) で削除したタスク以外の全要素を含む新しい配列を生成します。',
  },

  // ── api-custom-hook ──────────────────────────────────
  {
    id: 'api-custom-hook-daily-0',
    stepId: 'api-custom-hook',
    type: 'blank',
    prompt: 'データ取得ロジックをカスタムフックにまとめてください。\nfunction ____Tasks() {\n  const [tasks, setTasks] = useState([])\n  // fetch ロジック\n  return { tasks }\n}',
    answer: 'useFetch',
    hint: 'カスタムフックは use で始めます。',
    explanation: 'データ取得ロジックをカスタムフックに切り出すとコンポーネントがシンプルになり、同じロジックを複数の場所で再利用できます。',
  },
  {
    id: 'api-custom-hook-daily-1',
    stepId: 'api-custom-hook',
    type: 'choice',
    prompt: 'カスタムフックが返すべき値として適切なのはどれですか？',
    answer: '{ data, loading, error }',
    hint: 'データ取得の3つの状態を返します。',
    explanation: 'データ取得カスタムフックは data（取得データ）、loading（ローディング中フラグ）、error（エラー情報）の3つを返すのが一般的なパターンです。',
    choices: [
      '{ data, loading, error }',
      '[ data ]',
      'data のみ',
      '[ data, setData ]',
    ],
  },
  {
    id: 'api-custom-hook-daily-2',
    stepId: 'api-custom-hook',
    type: 'blank',
    prompt: 'フックのロード状態の初期値を設定してください。\nconst [loading, setLoading] = useState(____)',
    answer: 'true',
    hint: 'マウント直後からローディング中です。',
    explanation: 'loading の初期値を true にすることで、データ取得が完了するまでローディング UI を表示できます。',
  },

  // ── api-error-loading ────────────────────────────────
  {
    id: 'api-error-loading-daily-0',
    stepId: 'api-error-loading',
    type: 'blank',
    prompt: 'ローディング中にスピナーを表示してください。\nif (____) return <Spinner />',
    answer: 'loading',
    hint: 'ローディング状態の変数名です。',
    explanation: 'loading が true の間は早期リターンで Spinner を表示し、データが揃ってから本来のコンテンツを描画します。',
  },
  {
    id: 'api-error-loading-daily-1',
    stepId: 'api-error-loading',
    type: 'choice',
    prompt: 'エラー発生時にエラーメッセージを表示するパターンとして正しいのはどれですか？',
    answer: 'if (error) return <ErrorMessage message={error} />',
    hint: 'エラー状態のときに早期リターンします。',
    explanation: 'loading, error, data の順に確認し、それぞれの状態に応じた UI を早期リターンで返すパターンが一般的です。',
    choices: [
      'if (error) return <ErrorMessage message={error} />',
      'error && throw new Error(error)',
      'console.error(error)',
      'alert(error)',
    ],
  },
  {
    id: 'api-error-loading-daily-2',
    stepId: 'api-error-loading',
    type: 'blank',
    prompt: 'finally ブロックでローディング状態を解除してください。\ntry {\n  // fetch\n} catch (e) {\n  setError(e.message)\n} ____ {\n  setLoading(false)\n}',
    answer: 'finally',
    hint: '成功・失敗に関わらず必ず実行されるブロックです。',
    explanation: 'finally ブロックは try・catch のいずれの結果でも必ず実行されます。ローディング解除などの後処理を here に置くことで確実に実行されます。',
  },

  // ── ts-types ─────────────────────────────────────────
  {
    id: 'ts-types-daily-0',
    stepId: 'ts-types',
    type: 'blank',
    prompt: '変数 count に number 型のアノテーションを付けてください。\nconst count: ____ = 0',
    answer: 'number',
    hint: '整数・小数を含む数値の TypeScript プリミティブ型です。',
    explanation: 'TypeScript の number 型は整数・小数・NaN・Infinity を含むすべての数値を表します。変数名の後ろにコロンで型を指定します。',
  },
  {
    id: 'ts-types-daily-1',
    stepId: 'ts-types',
    type: 'choice',
    prompt: '文字列と null のどちらも格納できる型はどれですか？',
    answer: 'string | null',
    hint: 'ユニオン型を使います。',
    explanation: 'ユニオン型 string | null は string または null の値を取れます。null 許容の変数に使います。',
    choices: ['string | null', 'string & null', 'string?', 'Nullable<string>'],
  },
  {
    id: 'ts-types-daily-2',
    stepId: 'ts-types',
    type: 'blank',
    prompt: '文字列の配列型を指定してください。\nconst names: ____[] = [\'Alice\', \'Bob\']',
    answer: 'string',
    hint: '要素の型の後ろに [] を付けると配列型になります。',
    explanation: 'T[] または Array<T> で配列型を表します。string[] は文字列の配列、number[] は数値の配列です。',
  },

  // ── ts-functions ─────────────────────────────────────
  {
    id: 'ts-functions-daily-0',
    stepId: 'ts-functions',
    type: 'blank',
    prompt: '関数の戻り値の型を指定してください。\nfunction greet(name: string): ____ {\n  return \'Hello, \' + name\n}',
    answer: 'string',
    hint: '戻り値はどの型ですか？',
    explanation: '関数の引数リストの後ろにコロンで戻り値の型を指定します。戻り値がない場合は void を使います。',
  },
  {
    id: 'ts-functions-daily-1',
    stepId: 'ts-functions',
    type: 'choice',
    prompt: '戻り値がない関数の戻り値型はどれですか？',
    answer: 'void',
    hint: '何も返さないことを表す TypeScript の型です。',
    explanation: 'void は値を返さない関数の戻り値型です。undefined と似ていますが、意図的に何も返さないことを明示します。',
    choices: ['void', 'undefined', 'null', 'never'],
  },
  {
    id: 'ts-functions-daily-2',
    stepId: 'ts-functions',
    type: 'blank',
    prompt: 'オプショナルパラメータを定義してください。\nfunction log(message: string, level____ : string) { ... }',
    answer: '?',
    hint: 'パラメータ名の後ろに ? を付けるとオプショナルになります。',
    explanation: 'パラメータ名の後ろに ? を付けると省略可能なオプショナルパラメータになります。型は T | undefined になります。',
  },

  // ── ts-objects ───────────────────────────────────────
  {
    id: 'ts-objects-daily-0',
    stepId: 'ts-objects',
    type: 'blank',
    prompt: 'ユーザーオブジェクトの型を定義してください。\n____ User {\n  id: number\n  name: string\n}',
    answer: 'interface',
    hint: 'オブジェクトの形状を定義する TypeScript のキーワードです。',
    explanation: 'interface はオブジェクトの構造（プロパティと型）を定義します。type との違いは拡張（extends）の書き方などです。',
  },
  {
    id: 'ts-objects-daily-1',
    stepId: 'ts-objects',
    type: 'choice',
    prompt: 'プロパティをオプショナル（省略可能）にする記法はどれですか？',
    answer: 'age?: number',
    hint: 'プロパティ名の後ろに ? を付けます。',
    explanation: 'プロパティ名の後ろに ? を付けるとそのプロパティは省略可能になり、型は T | undefined になります。',
    choices: [
      'age?: number',
      'age: number | undefined',
      'optional age: number',
      'age?: number | null',
    ],
  },
  {
    id: 'ts-objects-daily-2',
    stepId: 'ts-objects',
    type: 'blank',
    prompt: '変更不可のプロパティを定義してください。\ninterface Config {\n  ____ apiUrl: string\n}',
    answer: 'readonly',
    hint: '値を変更できないプロパティにするキーワードです。',
    explanation: 'readonly を付けたプロパティは初期化後に値を変更できません。不変データの型定義に使います。',
  },

  // ── ts-union-narrowing ───────────────────────────────
  {
    id: 'ts-union-narrowing-daily-0',
    stepId: 'ts-union-narrowing',
    type: 'blank',
    prompt: '文字列か数値を受け取れるユニオン型を定義してください。\ntype StringOrNumber = string ____ number',
    answer: '|',
    hint: 'ユニオン型の区切り文字です。',
    explanation: 'パイプ | でユニオン型を作ります。string | number は文字列か数値のどちらかを受け取れる型です。',
  },
  {
    id: 'ts-union-narrowing-daily-1',
    stepId: 'ts-union-narrowing',
    type: 'choice',
    prompt: '型の絞り込みに typeof を使う場合、文字列かどうかを調べるコードはどれですか？',
    answer: 'typeof value === "string"',
    hint: 'typeof 演算子の比較に使う文字列リテラルです。',
    explanation: 'typeof value === "string" で value が文字列型かどうかを確認できます。TypeScript はこの分岐内で value を string 型として認識します。',
    choices: [
      'typeof value === "string"',
      'value instanceof String',
      'value.constructor === String',
      'isString(value)',
    ],
  },
  {
    id: 'ts-union-narrowing-daily-2',
    stepId: 'ts-union-narrowing',
    type: 'blank',
    prompt: 'in 演算子でオブジェクトのプロパティを確認して型を絞り込んでください。\nif (____ \'name\' in obj) {\n  // obj は name プロパティを持つ\n}',
    answer: '',
    hint: '追加のキーワードは不要です。in の前に何も書きません。',
    explanation: '"name" in obj で obj に name プロパティが存在するか確認します。TypeScript はこの分岐内でオブジェクトの型を絞り込みます。',
  },

  // ── ts-generics ──────────────────────────────────────
  {
    id: 'ts-generics-daily-0',
    stepId: 'ts-generics',
    type: 'blank',
    prompt: '任意の型を受け取る汎用関数を定義してください。\nfunction identity<____>(value: T): T {\n  return value\n}',
    answer: 'T',
    hint: 'ジェネリクスの型パラメータは慣例的に大文字1文字で表します。',
    explanation: '<T> で型パラメータを宣言します。T は任意の名前ですが Type の頭文字で T が慣例です。関数呼び出し時に型が決まります。',
  },
  {
    id: 'ts-generics-daily-1',
    stepId: 'ts-generics',
    type: 'choice',
    prompt: 'ジェネリクスに制約を付けて length プロパティを持つ型だけを受け付けるコードはどれですか？',
    answer: 'function len<T extends { length: number }>(arg: T)',
    hint: 'extends キーワードで制約を付けます。',
    explanation: 'T extends { length: number } とすることで T に length プロパティが存在することを保証します。',
    choices: [
      'function len<T extends { length: number }>(arg: T)',
      'function len<T implements { length: number }>(arg: T)',
      'function len<T : { length: number }>(arg: T)',
      'function len<T & { length: number }>(arg: T)',
    ],
  },
  {
    id: 'ts-generics-daily-2',
    stepId: 'ts-generics',
    type: 'blank',
    prompt: 'Promise の型引数でレスポンスの型を指定してください。\nasync function fetchUser(): ____<User> {\n  // ...\n}',
    answer: 'Promise',
    hint: '非同期関数の戻り値を表すジェネリック型です。',
    explanation: 'Promise<T> の T にレスポンスの型を指定することで、await の戻り値が正しく推論されます。',
  },

  // ── ts-utility-types ─────────────────────────────────
  {
    id: 'ts-utility-types-daily-0',
    stepId: 'ts-utility-types',
    type: 'blank',
    prompt: 'User 型の全プロパティをオプショナルにしてください。\ntype PartialUser = ____<User>',
    answer: 'Partial',
    hint: '全プロパティをオプショナルにするユーティリティ型です。',
    explanation: 'Partial<T> は T の全プロパティを ? 付き（省略可能）にした新しい型を作ります。更新用のフォームデータなどに使います。',
  },
  {
    id: 'ts-utility-types-daily-1',
    stepId: 'ts-utility-types',
    type: 'choice',
    prompt: 'オブジェクト型から特定のプロパティだけを取り出すユーティリティ型はどれですか？',
    answer: 'Pick',
    hint: 'ピックアップするイメージです。',
    explanation: 'Pick<T, K> は T 型から K で指定したプロパティだけを持つ新しい型を作ります。',
    choices: ['Pick', 'Omit', 'Partial', 'Required'],
  },
  {
    id: 'ts-utility-types-daily-2',
    stepId: 'ts-utility-types',
    type: 'blank',
    prompt: 'User 型から password プロパティを除いた型を作ってください。\ntype PublicUser = ____<User, \'password\'>',
    answer: 'Omit',
    hint: '指定したプロパティを除外するユーティリティ型です。',
    explanation: 'Omit<T, K> は T 型から K で指定したプロパティを除外した新しい型を作ります。センシティブなフィールドを除く公開用型の定義に便利です。',
  },

  // ── ts-react-props ───────────────────────────────────
  {
    id: 'ts-react-props-daily-0',
    stepId: 'ts-react-props',
    type: 'blank',
    prompt: 'コンポーネントの props の型を定義してください。\n____ ButtonProps {\n  label: string\n  onClick: () => void\n}',
    answer: 'interface',
    hint: 'Props の型定義に使う TypeScript のキーワードです。',
    explanation: 'interface で props の形状を定義します。type エイリアスを使っても同様に定義できます。',
  },
  {
    id: 'ts-react-props-daily-1',
    stepId: 'ts-react-props',
    type: 'choice',
    prompt: '子コンポーネントを受け取る children の型として適切なのはどれですか？',
    answer: 'React.ReactNode',
    hint: 'JSX 要素・文字列・null など React が描画できる値を表す型です。',
    explanation: 'React.ReactNode は JSX 要素・文字列・数値・null・undefined など React が描画できるすべての値を表す型です。children の型として最も汎用的です。',
    choices: [
      'React.ReactNode',
      'React.Element',
      'JSX.Element',
      'React.Component',
    ],
  },
  {
    id: 'ts-react-props-daily-2',
    stepId: 'ts-react-props',
    type: 'blank',
    prompt: 'props の型を付けてコンポーネントを定義してください。\nfunction Greeting({ name }: ____) {\n  return <h1>Hello, {name}</h1>\n}',
    answer: 'GreetingProps',
    hint: 'コンポーネント名 + Props という命名が慣例です。',
    explanation: 'props の型名は「コンポーネント名 + Props」とするのが一般的な命名規則です。分割代入した引数にアノテーションを付けます。',
  },

  // ── ts-react-state ───────────────────────────────────
  {
    id: 'ts-react-state-daily-0',
    stepId: 'ts-react-state',
    type: 'blank',
    prompt: '文字列の状態を型引数付きで定義してください。\nconst [name, setName] = useState<____>(\'\')',
    answer: 'string',
    hint: 'useState に型引数を渡します。',
    explanation: 'useState<string>(\'\') と型引数を明示することで、setName に string 以外の値を渡すとコンパイルエラーになります。',
  },
  {
    id: 'ts-react-state-daily-1',
    stepId: 'ts-react-state',
    type: 'choice',
    prompt: 'null か User オブジェクトを格納できる状態の型引数はどれですか？',
    answer: 'User | null',
    hint: 'ユニオン型で null 許容にします。',
    explanation: 'useState<User | null>(null) で未取得（null）か取得済み（User）かを型安全に表せます。',
    choices: [
      'User | null',
      'User?',
      'Maybe<User>',
      'Nullable<User>',
    ],
  },
  {
    id: 'ts-react-state-daily-2',
    stepId: 'ts-react-state',
    type: 'blank',
    prompt: '初期値から型が推論される場合でも明示的に型引数を付けてください。\nconst [count, setCount] = useState<____>(0)',
    answer: 'number',
    hint: '数値型のプリミティブです。',
    explanation: 'useState(0) だけでも number と推論されますが、useState<number>(0) と明示するとコードの意図が明確になります。',
  },

  // ── ts-react-hooks ───────────────────────────────────
  {
    id: 'ts-react-hooks-daily-0',
    stepId: 'ts-react-hooks',
    type: 'blank',
    prompt: 'DOM の input 要素への参照を型付きで作ってください。\nconst inputRef = useRef<____>(null)',
    answer: 'HTMLInputElement',
    hint: 'HTML の input 要素の型です。',
    explanation: 'useRef<HTMLInputElement>(null) とすることで inputRef.current が HTMLInputElement 型になり、focus() などのメソッドの型補完が効きます。',
  },
  {
    id: 'ts-react-hooks-daily-1',
    stepId: 'ts-react-hooks',
    type: 'choice',
    prompt: 'useCallback の戻り値型はどれですか？',
    answer: 'メモ化されたコールバック関数',
    hint: 'useCallback は関数をメモ化します。',
    explanation: 'useCallback は渡した関数をメモ化して返します。依存配列が変化しない限り同じ関数参照を返します。',
    choices: [
      'メモ化されたコールバック関数',
      'void',
      '関数の戻り値',
      'boolean',
    ],
  },
  {
    id: 'ts-react-hooks-daily-2',
    stepId: 'ts-react-hooks',
    type: 'blank',
    prompt: 'useReducer の型引数で状態の型とアクションの型を指定してください。\nconst [state, dispatch] = useReducer<____<State, Action>>(reducer, initialState)',
    answer: 'Reducer',
    hint: 'React の Reducer 型です。',
    explanation: 'useReducer<Reducer<State, Action>>(reducer, initialState) と型引数を指定することで state と dispatch の型が正しく推論されます。',
  },

  // ── ts-react-events ──────────────────────────────────
  {
    id: 'ts-react-events-daily-0',
    stepId: 'ts-react-events',
    type: 'blank',
    prompt: 'input の onChange ハンドラの引数に型を付けてください。\nconst handleChange = (e: React.____<HTMLInputElement>) => { ... }',
    answer: 'ChangeEvent',
    hint: 'onChange イベントに対応する React の型です。',
    explanation: 'React.ChangeEvent<HTMLInputElement> は input 要素の onChange イベントオブジェクトの型です。e.target.value で入力値を取得します。',
  },
  {
    id: 'ts-react-events-daily-1',
    stepId: 'ts-react-events',
    type: 'choice',
    prompt: 'ボタンの onClick ハンドラの引数の型はどれですか？',
    answer: 'React.MouseEvent<HTMLButtonElement>',
    hint: 'マウスイベントの型です。',
    explanation: 'React.MouseEvent<HTMLButtonElement> はボタンのクリックイベントの型です。クリック位置などのマウス情報にアクセスできます。',
    choices: [
      'React.MouseEvent<HTMLButtonElement>',
      'React.ClickEvent<HTMLButtonElement>',
      'Event',
      'MouseEventHandler',
    ],
  },
  {
    id: 'ts-react-events-daily-2',
    stepId: 'ts-react-events',
    type: 'blank',
    prompt: 'フォーム送信イベントの型を付けてください。\nconst handleSubmit = (e: React.____<HTMLFormElement>) => { ... }',
    answer: 'FormEvent',
    hint: 'フォーム送信イベントに対応する React の型です。',
    explanation: 'React.FormEvent<HTMLFormElement> はフォームの onSubmit イベントオブジェクトの型です。e.preventDefault() を呼ぶためのイベントを受け取ります。',
  },

  // ── error-boundary ───────────────────────────────────
  {
    id: 'error-boundary-daily-0',
    stepId: 'error-boundary',
    type: 'blank',
    prompt: 'エラーバウンダリでエラーをキャッチするライフサイクルメソッドを完成させてください。\nstatic getDerivedStateFromError(error) {\n  return { ____: true }\n}',
    answer: 'hasError',
    hint: 'エラー発生状態を示す状態プロパティです。',
    explanation: 'getDerivedStateFromError はエラーを受け取り新しい状態を返します。{ hasError: true } を返すことでエラー UI を表示する準備をします。',
  },
  {
    id: 'error-boundary-daily-1',
    stepId: 'error-boundary',
    type: 'choice',
    prompt: 'エラーバウンダリが実装されている場合、子コンポーネントでエラーが発生したときの動作はどれですか？',
    answer: 'エラーバウンダリの fallback UI が表示される',
    hint: 'エラーが上位にバブルアップします。',
    explanation: 'エラーバウンダリは子コンポーネントツリーの JavaScript エラーをキャッチし、フォールバック UI を表示します。アプリ全体のクラッシュを防ぎます。',
    choices: [
      'エラーバウンダリの fallback UI が表示される',
      'アプリ全体がクラッシュする',
      'エラーは無視される',
      'ページがリロードされる',
    ],
  },
  {
    id: 'error-boundary-daily-2',
    stepId: 'error-boundary',
    type: 'blank',
    prompt: 'エラーバウンダリでエラーのログを記録するメソッドを完成させてください。\ncomponent____Catch(error, errorInfo) {\n  logError(error, errorInfo)\n}',
    answer: 'DidCatch',
    hint: 'エラーをキャッチした後に呼ばれるライフサイクルメソッドです。',
    explanation: 'componentDidCatch(error, errorInfo) でエラーの詳細情報を受け取り、ログサービスへの送信などを行えます。',
  },

  // ── suspense-lazy ────────────────────────────────────
  {
    id: 'suspense-lazy-daily-0',
    stepId: 'suspense-lazy',
    type: 'blank',
    prompt: 'コンポーネントを遅延読み込みしてください。\nconst LazyPage = React.____(()=> import(\'./LazyPage\'))',
    answer: 'lazy',
    hint: '動的インポートと組み合わせる React の関数です。',
    explanation: 'React.lazy() は動的インポートを受け取り、遅延ロードされるコンポーネントを返します。Suspense と組み合わせて使います。',
  },
  {
    id: 'suspense-lazy-daily-1',
    stepId: 'suspense-lazy',
    type: 'choice',
    prompt: 'Suspense でローディング中に表示する内容を指定するプロパティはどれですか？',
    answer: 'fallback',
    hint: 'ローディング中の代替コンテンツを指定します。',
    explanation: 'Suspense の fallback prop に Promise が解決されるまで表示するコンテンツ（ローディングスピナーなど）を指定します。',
    choices: ['fallback', 'loading', 'placeholder', 'pending'],
  },
  {
    id: 'suspense-lazy-daily-2',
    stepId: 'suspense-lazy',
    type: 'blank',
    prompt: 'lazy コンポーネントを Suspense でラップしてください。\n<____ fallback={<Spinner />}>\n  <LazyComponent />\n</____>',
    answer: 'Suspense',
    hint: 'React の組み込みコンポーネントです。',
    explanation: 'Suspense は遅延読み込みコンポーネントや非同期処理の待機中にフォールバック UI を表示します。',
  },

  // ── concurrent-features ──────────────────────────────
  {
    id: 'concurrent-features-daily-0',
    stepId: 'concurrent-features',
    type: 'blank',
    prompt: 'UI の更新を非緊急としてマークするトランジションを開始してください。\nconst [isPending, ____] = useTransition()',
    answer: 'startTransition',
    hint: 'useTransition が返す関数の名前です。',
    explanation: 'useTransition は [isPending, startTransition] を返します。startTransition の中で状態更新を行うと React が非緊急な更新として扱います。',
  },
  {
    id: 'concurrent-features-daily-1',
    stepId: 'concurrent-features',
    type: 'choice',
    prompt: 'useTransition の isPending が true の場合、何を意味しますか？',
    answer: 'トランジション更新が進行中',
    hint: 'pending は「保留中」という意味です。',
    explanation: 'isPending は startTransition で開始した更新がまだ完了していないことを示します。この間にローディング UI を表示できます。',
    choices: [
      'トランジション更新が進行中',
      '通常の状態更新が完了した',
      'コンポーネントがマウントされた',
      'エラーが発生した',
    ],
  },
  {
    id: 'concurrent-features-daily-2',
    stepId: 'concurrent-features',
    type: 'blank',
    prompt: '非緊急な状態更新を startTransition でラップしてください。\n____(()=> {\n  setSearchQuery(input)\n})',
    answer: 'startTransition',
    hint: 'useTransition から取得した関数です。',
    explanation: 'startTransition に状態更新のコールバックを渡すと、その更新を非緊急として扱います。キーボード入力などの緊急更新が優先されます。',
  },

  // ── use-optimistic ───────────────────────────────────
  {
    id: 'use-optimistic-daily-0',
    stepId: 'use-optimistic',
    type: 'blank',
    prompt: '楽観的更新フックを初期化してください。\nconst [optimisticTodos, ____] = useOptimistic(todos)',
    answer: 'addOptimistic',
    hint: '楽観的な状態を追加する関数です（慣例的な命名）。',
    explanation: 'useOptimistic は [楽観的状態, 更新関数] を返します。更新関数を呼ぶと即座に UI が更新され、サーバー処理完了後に実際の状態に戻ります。',
  },
  {
    id: 'use-optimistic-daily-1',
    stepId: 'use-optimistic',
    type: 'choice',
    prompt: '楽観的更新の主なメリットはどれですか？',
    answer: 'サーバーのレスポンスを待たずに UI を即時更新できる',
    hint: '「楽観的」とはサーバーが成功すると仮定することです。',
    explanation: '楽観的更新はサーバー処理の成功を前提に UI を先に更新します。レスポンスを待つ間のローディング感をなくしスムーズな UX を実現します。',
    choices: [
      'サーバーのレスポンスを待たずに UI を即時更新できる',
      'サーバーエラーを防ぐことができる',
      'API リクエストの回数を減らせる',
      'データの整合性を保証できる',
    ],
  },
  {
    id: 'use-optimistic-daily-2',
    stepId: 'use-optimistic',
    type: 'blank',
    prompt: '楽観的状態を使って UI を描画してください。\nreturn ____Todos.map(todo => <TodoItem key={todo.id} todo={todo} />)',
    answer: 'optimistic',
    hint: '楽観的な状態変数の名前です。',
    explanation: 'useOptimistic が返す optimisticTodos を使ってリストを描画すると、サーバーレスポンス前でも UI が即時更新されます。',
  },

  // ── portals ──────────────────────────────────────────
  {
    id: 'portals-daily-0',
    stepId: 'portals',
    type: 'blank',
    prompt: 'ポータルを使って DOM の別の場所にコンポーネントを描画してください。\nreturn ReactDOM.____(children, document.getElementById(\'modal-root\'))',
    answer: 'createPortal',
    hint: 'ポータルを作る ReactDOM の関数です。',
    explanation: 'ReactDOM.createPortal(children, container) は children を React ツリーの外側の container DOM 要素にレンダリングします。',
  },
  {
    id: 'portals-daily-1',
    stepId: 'portals',
    type: 'choice',
    prompt: 'ポータルの主な用途はどれですか？',
    answer: 'モーダル・ツールチップなど親の overflow/z-index の影響を受けたくないUI要素',
    hint: 'CSS のスタックコンテキストを超える必要があります。',
    explanation: 'ポータルは親の CSS（overflow: hidden や z-index）の影響を受けずに描画したい UI（モーダル、ドロップダウン、ツールチップ等）に使います。',
    choices: [
      'モーダル・ツールチップなど親の overflow/z-index の影響を受けたくないUI要素',
      'コンポーネントのパフォーマンス最適化',
      'サーバーサイドレンダリングの補助',
      'コンテキストの共有',
    ],
  },
  {
    id: 'portals-daily-2',
    stepId: 'portals',
    type: 'blank',
    prompt: 'ポータルのマウント先 DOM 要素を取得してください。\nconst portalRoot = document.____(\'portal-root\')',
    answer: 'getElementById',
    hint: 'ID で DOM 要素を取得するメソッドです。',
    explanation: 'document.getElementById で HTML に用意したポータルのマウント先コンテナを取得します。通常は index.html に <div id="portal-root"> を追加します。',
  },

  // ── forward-ref ──────────────────────────────────────
  {
    id: 'forward-ref-daily-0',
    stepId: 'forward-ref',
    type: 'blank',
    prompt: 'ref を転送するコンポーネントを定義してください。\nconst Input = React.____(function Input(props, ref) {\n  return <input ref={ref} {...props} />\n})',
    answer: 'forwardRef',
    hint: 'ref 転送を可能にする React の関数です。',
    explanation: 'React.forwardRef でラップすることでコンポーネントが ref prop を受け取り、内部の DOM 要素に渡せるようになります。',
  },
  {
    id: 'forward-ref-daily-1',
    stepId: 'forward-ref',
    type: 'choice',
    prompt: 'forwardRef の主な用途はどれですか？',
    answer: '親コンポーネントから子コンポーネント内の DOM 要素を直接操作する',
    hint: '外部からの DOM 操作を可能にします。',
    explanation: 'forwardRef により親から ref を渡して子コンポーネント内の DOM 要素（input, div など）にアクセスし、focus() などを呼び出せます。',
    choices: [
      '親コンポーネントから子コンポーネント内の DOM 要素を直接操作する',
      'コンポーネント間でコンテキストを共有する',
      'コンポーネントのレンダリングを最適化する',
      'コンポーネントの状態をリセットする',
    ],
  },
  {
    id: 'forward-ref-daily-2',
    stepId: 'forward-ref',
    type: 'blank',
    prompt: '子コンポーネントから親に公開するメソッドを定義してください。\nuseImperativeHandle(ref, () => ({\n  ____: () => inputRef.current?.focus()\n}))',
    answer: 'focus',
    hint: '外部に公開するメソッド名です（例）。',
    explanation: 'useImperativeHandle で ref に公開するメソッドを明示的に定義できます。実装の詳細を隠しつつ必要なメソッドだけを親に公開します。',
  },

  // ── rhf-zod ──────────────────────────────────────────
  {
    id: 'rhf-zod-daily-0',
    stepId: 'rhf-zod',
    type: 'blank',
    prompt: 'React Hook Form を初期化してください。\nconst { register, handleSubmit } = ____()',
    answer: 'useForm',
    hint: 'React Hook Form のメインフックです。',
    explanation: 'useForm() で register（フィールド登録）・handleSubmit（送信処理）・formState などが含まれたオブジェクトが返されます。',
  },
  {
    id: 'rhf-zod-daily-1',
    stepId: 'rhf-zod',
    type: 'choice',
    prompt: 'Zod スキーマを React Hook Form のバリデーターとして使うためのアダプターはどれですか？',
    answer: 'zodResolver',
    hint: '@hookform/resolvers/zod からインポートします。',
    explanation: 'zodResolver(schema) を useForm の resolver オプションに渡すことで、Zod の型安全なバリデーションを RHF と統合できます。',
    choices: [
      'zodResolver',
      'zodAdapter',
      'zodValidate',
      'zodForm',
    ],
  },
  {
    id: 'rhf-zod-daily-2',
    stepId: 'rhf-zod',
    type: 'blank',
    prompt: 'フォームの送信を処理してください。\n<form onSubmit={____(onSubmit)}>',
    answer: 'handleSubmit',
    hint: 'useForm が返す送信ハンドラーラッパー関数です。',
    explanation: 'handleSubmit(onSubmit) で RHF がバリデーション実行後に成功した場合のみ onSubmit コールバックを呼びます。e.preventDefault() も自動処理します。',
  },

  // ── pagination ───────────────────────────────────────
  {
    id: 'pagination-daily-0',
    stepId: 'pagination',
    type: 'blank',
    prompt: '現在のページに対応するデータを取得してください。\nconst start = (currentPage - 1) * pageSize\nconst pageData = allData.____(start, start + ____)',
    answer: 'slice',
    hint: '配列の一部を切り出すメソッドです。',
    explanation: 'slice(start, end) で配列から指定範囲の要素を取り出します。ページネーションでは (page-1)*size 〜 page*size の範囲を切り出します。',
  },
  {
    id: 'pagination-daily-1',
    stepId: 'pagination',
    type: 'choice',
    prompt: '総ページ数を計算する式はどれですか？',
    answer: 'Math.ceil(totalItems / pageSize)',
    hint: '小数点以上に切り上げます。',
    explanation: '総アイテム数をページサイズで割り、Math.ceil で切り上げることで全アイテムを表示するのに必要なページ数が求まります。',
    choices: [
      'Math.ceil(totalItems / pageSize)',
      'Math.floor(totalItems / pageSize)',
      'totalItems / pageSize',
      'Math.round(totalItems / pageSize)',
    ],
  },
  {
    id: 'pagination-daily-2',
    stepId: 'pagination',
    type: 'blank',
    prompt: '前のページに移動する処理を実装してください。\nconst handlePrev = () => {\n  setCurrentPage(prev => Math.max(prev - 1, ____))\n}',
    answer: '1',
    hint: 'ページ番号の最小値です。',
    explanation: 'Math.max(prev - 1, 1) で1ページ目より前に戻らないようにします。境界値チェックは安全なページネーション実装の基本です。',
  },

  // ── infinite-scroll ──────────────────────────────────
  {
    id: 'infinite-scroll-daily-0',
    stepId: 'infinite-scroll',
    type: 'blank',
    prompt: '要素が画面に入ったことを検知する Web API を使ってください。\nconst observer = new ____(callback)',
    answer: 'IntersectionObserver',
    hint: '要素の可視状態を監視する Web API です。',
    explanation: 'IntersectionObserver は要素がビューポートに入ったか出たかを非同期に監視します。無限スクロールのトリガーに使います。',
  },
  {
    id: 'infinite-scroll-daily-1',
    stepId: 'infinite-scroll',
    type: 'choice',
    prompt: '追加データがあるかどうかを管理する状態変数の名前として適切なのはどれですか？',
    answer: 'hasMore',
    hint: 'まだ読み込むデータがあるかを示します。',
    explanation: 'hasMore（boolean）で追加読み込みが可能かを管理します。false になったら IntersectionObserver の観測を停止してトリガーを無効化します。',
    choices: [
      'hasMore',
      'isEnd',
      'canLoad',
      'dataLeft',
    ],
  },
  {
    id: 'infinite-scroll-daily-2',
    stepId: 'infinite-scroll',
    type: 'blank',
    prompt: '追加読み込みしたデータを既存リストに連結してください。\nsetItems(prev => [____, ...newItems])',
    answer: '...prev',
    hint: 'スプレッド構文で前の配列を展開します。',
    explanation: 'スプレッド構文 ...prev で既存アイテムを展開し末尾に newItems を結合します。逆順 ...newItems, ...prev なら先頭に追加します。',
  },

  // ── auth-flow ────────────────────────────────────────
  {
    id: 'auth-flow-daily-0',
    stepId: 'auth-flow',
    type: 'blank',
    prompt: 'Supabase でメール・パスワードでサインインしてください。\nconst { error } = await supabase.auth.____({{ email, password }})',
    answer: 'signInWithPassword',
    hint: 'Supabase Auth のログインメソッドです。',
    explanation: 'supabase.auth.signInWithPassword({ email, password }) でメール・パスワード認証を実行します。error が null なら成功です。',
  },
  {
    id: 'auth-flow-daily-1',
    stepId: 'auth-flow',
    type: 'choice',
    prompt: 'Supabase の認証状態の変化を監視するメソッドはどれですか？',
    answer: 'supabase.auth.onAuthStateChange',
    hint: 'ログイン・ログアウト時に呼ばれるリスナーです。',
    explanation: 'onAuthStateChange は SIGNED_IN・SIGNED_OUT などのイベントと現在のセッションをコールバックで受け取ります。AuthContext の初期化に使います。',
    choices: [
      'supabase.auth.onAuthStateChange',
      'supabase.auth.subscribe',
      'supabase.auth.listen',
      'supabase.auth.watch',
    ],
  },
  {
    id: 'auth-flow-daily-2',
    stepId: 'auth-flow',
    type: 'blank',
    prompt: 'Supabase でサインアウトしてください。\nawait supabase.auth.____()',
    answer: 'signOut',
    hint: 'Supabase Auth のログアウトメソッドです。',
    explanation: 'supabase.auth.signOut() でサインアウトします。セッションが削除され onAuthStateChange で SIGNED_OUT イベントが発火します。',
  },
]
